### PR TITLE
Authenticated fetch not allowed

### LINKED ISSUE #71: Test query doesn't work when logged in
Error `Cross-Origin Request Blocked: The Same Origin Policy disallows reading the remote resource at https://fragments.dbpedia.org/2016-04/en. (Reason: header ‘authorization’ is not allowed according to header ‘Access-Control-Allow-Headers’ from CORS preflight response)`

### PR DESCRIPTION
**Pull request by AronBuzogany**
This PR Fixes #71 by doing the following:

- Try to fetch the resource unauthenticated. 
- If it fails, or returns status code 401 or 403 AND user is logged in, try it authenticated

### CODE REVIEW

**Comment by pheyvaer** [comment]
This is what the authentication library already does. In other words, this code adds something is already done.

File: src/right-field/RightField.jsx [hunk 1]
```diff
@@ -267,6 +272,27 @@ async function executeQuery(query, eventEmitter, resultAdder) {
   }
 }
 
+/**
+ * Tries to fetch a query onauthenticated, if it fails it tries to fetch it authenticated.
+ * @param {String || URL} argument a URL or a string that should be fetched
+ * @returns {Response} the response from the fetch
+ */
+async function authenticationFetch(argument) {
```
Comment (bjdmeest) [inline src/right-field/RightField.jsx:280]: This feels very inefficient. There's no other way of fixing this?
Also, when commenting on stuff, also include the reasoning on why you do it like this, in this case because there's an issue with authenticated fetches on open data

**Comment by AronBuzogany** [comment]
> This is what the authentication library already does. In other words, this code adds something that is already done.

This did resolve it though, the Web application now no longer calls an error on the test query when logged in

**Comment by pheyvaer** [comment]
> > This is what the authentication library already does. In other words, this code adds something that is already done.
> 
> This did resolve it though, the Web application now no longer calls an error on the test query when logged in

That might be the case, but in general it's not a good practice to change your code to fix an issue in another library or server. It could be a temporary fix, but in this case we don't have a full understanding of where the issue is coming from. In other words, which component is causing it?

Regarding the CORS headers, Comunica offers to option to pass a [proxy](https://comunica.dev/docs/query/advanced/proxying/). It would suggest trying this and adding this to the config file.

**Comment by AronBuzogany** [comment]
> That might be the case, but in general it's not a good practice to change your code to fix an issue in another library or server.

I understand, I thought you meant that Comunica already does exactly what I do.

**Comment by pheyvaer** [comment]
> > That might be the case, but in general it's not a good practice to change your code to fix an issue in another library or server.
> 
> I understand, I thought you meant that Comunica already does exactly what I do.

No, the **authentication library** does that. Comunica just uses the fetch.

**Comment by AronBuzogany** [comment]
> Regarding the CORS headers, Comunica offers to option to pass a [proxy](https://comunica.dev/docs/query/advanced/proxying/). 

I've looked into this. Which proxy should we use though?

File: package.json [hunk 2]
```diff
@@ -3,11 +3,12 @@
   "version": "0.1.0",
   "private": true,
   "dependencies": {
+    "@comunica/actor-http-proxy": "^2.8.1",
     "@comunica/query-sparql": "^2.6.9",
-    "@solid/community-server": "^6.0.1",
     "@inrupt/solid-client": "^1.29.0",
     "@inrupt/solid-client-authn-browser": "^1.17.1",
     "@inrupt/vocab-common-rdf": "^1.0.5",
+    "@solid/community-server": "^6.0.1",
```
Comment (pheyvaer) [inline package.json:11]: Shouldn't this only be a dev dependency?

File: README.md [hunk 3]
```diff
@@ -54,6 +54,7 @@ The configuration file follows a simple structure.
     "showMilliseconds", "True or false, whether the Runtime section should show milliseconds or not.",
     "defaultIDP": "The default value used for IDP when logging in, this IDP can be manually changed in the Web app as well. ",
     "queryFolder": "The base location of the queries, all query locations will start from this folder (relative to public folder.)",
+    "httpProxy": "The http proxy used to execute queries. When left empty, the Comunica query engine will handle it.",
```
Comment (pheyvaer) [inline README.md:57]: When using the proxy Comunica will still execute the query, it will only reroute the request via the proxy. This has to be fixed this. Additionally mention that it is mainly done here to deal with CORS headers that are not (correctly) set on the servers that are being queried.

**Review by pheyvaer — CHANGES_REQUESTED** [review]

File: package.json (hunk 2 above)
Comment (AronBuzogany) [reply package.json]: Correct. This was an app dependency when trying to solve #51 , but I forgot to change it. It is now made a dev dependency in [commit 0088b1c](https://github.com/SolidLabResearch/generic-data-viewer/pull/72/commits/0088b1c8e0382449c0df06862b67c79031437903)

File: README.md (hunk 3 above)
Comment (AronBuzogany) [reply README.md]: I have updated the explanation accordingly in [commit 0e07459](https://github.com/SolidLabResearch/generic-data-viewer/pull/72/commits/0e07459756a7b46c929c9db4e3a653751415a237)

**Review by pheyvaer — APPROVED** [review]
